import { ethereumTestnet } from '@/types/networks';
import { DAO } from '../types/atomState';
import { nounsDAOQuestItems, uniswapDAOQuestItems } from './mock-quest';

export const mockeDAOs: DAO[] = [
  {
    id: `0x123da`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2Fd9e8442f-5cb7-4357-9567-3cdd7ae5930e_400x400.jpg&w=384&q=75`,
    name: `Uniswap`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 32,
    holdersCount: 366,
    votersCount: 323,
    questItems: uniswapDAOQuestItems,
  },
  {
    id: `0x123daa`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.tally.xyz%2F6b7f8135-d235-41c8-827b-ee8eecc5a2b2_original.png&w=384&q=75`,

    name: `LilNouns`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 106,
    holdersCount: 366,
    questItems: nounsDAOQuestItems,
    votersCount: 323,
  },
  {
    id: `0x12dasda3`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2F6b1e8e31-de1d-425f-a46d-634c0d1e230e_400x400.jpg&w=384&q=75`,
    name: `DopeWars`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 41,
    holdersCount: 366,
    votersCount: 323,
  },

  {
    id: `0x12cdada3`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2F1decbb17-b472-4eb9-9141-92c3f86770de_400x400.jpg&w=384&q=75`,
    name: `Nouns DAO`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 237,
    holdersCount: 366,
    votersCount: 323,
  },

  {
    id: `0x123cdasaw`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2F9c5c9d1a-2fa7-4860-8516-bd958acfc22a_400x400.jpg&w=384&q=75`,
    name: `Silo`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 13,
    holdersCount: 366,
    votersCount: 323,
  },
  {
    id: `0x12s3`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2F52dcc4c6-eac8-4ce4-b50e-a258a21abd7e_400x400.jpg&w=384&q=75`,
    name: `ENS`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 45,
    holdersCount: 366,
    votersCount: 323,
  },

  {
    id: `0x12333`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.withtally.com%2F52fdf6fc-c2a4-4539-b36f-16c47f4c7de9_400x400.jpg&w=384&q=75`,
    name: `Gitcoin`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 3,
    holdersCount: 366,
    votersCount: 323,
  },

  {
    id: `0x123`,
    tallyUrl: `https://www.tally.xyz/gov/nounsdao`,
    iconImage: `https://www.tally.xyz/_next/image?url=https%3A%2F%2Fstatic.tally.xyz%2F6b7f8135-d235-41c8-827b-ee8eecc5a2b2_original.png&w=384&q=75`,
    name: `Sample DAO`,
    description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    holders: 0,
    votes: 0,
    network: ethereumTestnet,
    proposalsCount: 2,
    holdersCount: 366,
    votersCount: 323,
  },
];
